### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by anas10** [Akkyie/AKPickerView-Swift#1]
Since [Cocoapods 0.36](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) swift is supported. Can you please update your project to support cocoapods with this swift version ? 

Thanks.

**Comment by akkyie** [comment]
Thank you for waiting; now you can use AKPickerView through CocoaPods!
Please see how in the [README](https://github.com/Akkyie/AKPickerView-Swift#installation).
