### ISSUE TITLE
Framework Error when adding pod.

### ISSUE THREAD

**Issue by omarps** [Akkyie/AKPickerView-Swift#16]
I got this error when adding pod dependency:
[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it.

**Comment by akkyie** [comment]
Try adding `use_frameworks!` to your Podfile, like:

```
use_frameworks!
pod "AKPickerView-Swift"
```

**Comment by akkyie** [comment]
Perhaps your problem is solved?
Comment if you need any additional support.
