### ISSUE TITLE
What we put in "<#frame#>" ...

### ISSUE THREAD

**Issue by ghost** [Akkyie/AKPickerView-Swift#17]
Hi !  :)
I'm a beginner in swift and my problem is that I don't know what we have to put in "<#frame#>" at the line self.pickerView = AKPickerView(frame: <#frame#>)...
thank you in advance for your answers !

**Comment by akkyie** [comment]
It's a frame of AKPickerView. You can pass the frame as CGRect like:

```
let frame = CGRectMake(50, 100, 150, 200)
self.pickerView = AKPickerView(frame: frame)
```

It means you put AKPickerView on 50px from left edge, 100px from top edge, 150px width and 200px height.
