### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by derwaldgeist** [Akkyie/AKPickerView-Swift#18]
If I try to run this in Xcode 7 beta 4, I get 9 compilation errors. Maybe the Swift language framework has changed in the meantime?

**Comment by akkyie** [comment]
Since it's still in beta, Xcode 7 is not completely supported yet. Try [Swift 2.0 branch](https://github.com/Akkyie/AKPickerView-Swift/tree/swift2.0) instead.
