### ISSUE TITLE
Access control when using Cocoapods

### ISSUE THREAD

**Issue by sam899** [Akkyie/AKPickerView-Swift#2]
When using cocoapods, the datasource, delegate and other properties are unavailable.

They are currently internal (i.e. can be accessed only within the AKPickerView module)

They should be set to public to allow access outside of the AKPickerView module

**Comment by akkyie** [comment]
I'm ashamed of such a tiny mistake... I fixed (de84117ea148bdda8e0a4114b9d4dc52e7c2374b .)

Thanks for your report!
