### ISSUE TITLE
Many errors in Swift 2

### ISSUE THREAD

**Issue by kweles** [Akkyie/AKPickerView-Swift#27]
Hi Akkyie!

I think this component is not ready to use with swift 2.0
Someday will be possible?

Thanks!

**Comment by akkyie** [comment]
Check if you are using AKPickerView 1.0.0.
Your Podfile may look like:

```
target 'YourApp' do
  pod "AKPickerView-Swift", "~> 1.0.0"
end
```

**Comment by kweles** [comment]
Thanks Akkie!
