### ISSUE TITLE
pickerView custom class

### ISSUE THREAD

**Issue by corbrink** [Akkyie/AKPickerView-Swift#32]
In your example on the storyboard your picker view has a custom class assigned as AKPickerView instead of UIPickerView.
I cannot make this assignment when implementing the picker view in my project. How do I do this?

**Comment by corbrink** [comment]
Managed to enter the custom class for the pickerView in the identity inspector.
However when running the code the app crashes with comment:
"Unknown class AKPickerView in Interface Builder file."

**Comment by zachlucas** [comment]
@corbrink to fix this issue, specify the AKPickerView module in interface builder, it's the field right under the class field

**Comment by bennokress** [comment]
@zachlucas i know this is old, but i have the same problem and judging from stackoverflow and issues from other UIKit frameworks, your solution seems to be correct. however, i can't find out the right module name. i tried: AKPickerView, AKPickerView-Swift, AKPickerView.framework and the name of my app ... everything fails and i'm slowly giving up here. can you tell me what exactly to type in the Module field in IB?
