### ISSUE TITLE
automaticallyAdjustsScrollViewInsets

### ISSUE THREAD

**Issue by Katafalkas** [Akkyie/AKPickerView-Swift#7]
Hey, 

Just a small tip i have figured out:
If one of the parent view controllers of AKPickerView has `self.automaticallyAdjustsScrollViewInsets = true`, It might mess up `AKPickerView's` `collectionView` and you will get:

```
the behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values.
```

error. Beware ! :)

**Comment by akkyie** [comment]
Yes, this is a repeatedly reported problem in the Obj-C version (cf. Akkyie/AKPickerView#13, Akkyie/AKPickerView#37.) And I've regarded it as one of annoying _specifications_ of iOS, so I'm currently NOT working on this issue to solve. I'm closing it but if you think it must be solved, don't hesitate to reopen it. Of course pull requests are welcomed if you find any way to solve!
