### ISSUE TITLE
Last item is not aligned properly

### ISSUE THREAD

**Issue by Gob-Lin** [Akkyie/AKPickerView-Swift#8]
Hello there,

I have noticed an issue in your otherwise excellent picker: the last item of the collection is always misaligned (see attached image). This happens both in Wheel and Flat mode.

![img_0016](https://cloud.githubusercontent.com/assets/3015630/7470645/070dedf0-f31f-11e4-9a91-88615a8d9676.PNG)

Furthermore, I keep getting these warnings at runtime: 

the behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values. Please check the values return by the delegate.

Any suggestions?

Thanks.

**Comment by akkyie** [comment]
Did you try `self.automaticallyAdjustsScrollViewInsets = true` in your view controller?
Often it helps you solve the glitch.

**Comment by Gob-Lin** [comment]
Perfect! Thank you!

**Comment by akkyie** [comment]
I'm grad to here that!

**Comment by luisfelipesv** [comment]
I have the same bug but `self.automaticallyAdjustsScrollViewInsets = true` didn't solved it.
Actually in my case `self.automaticallyAdjustsScrollViewInsets = false`solve it
