### ISSUE TITLE
delegate and datasource are not weak referenced and cause retain cycle

### ISSUE THREAD

**Issue by natwales** [Akkyie/AKPickerView-Swift#9]
I am debugging a memory issue in my app and it appears, initially, that the datasource and delegate meathods in AKPickerView.swift are creating strong references back to my view controller that is causing it not to be de allocated.  I changed lines 232 and 234 and 193 from 

public var delegate:WHATEVER 
to 
weak var delegate:WHATEVER 

and that cleared up the retain cycle.

I've been confused about when delegates in Swift need to be weak referenced and when they don't. I believe because your protocols are defined with @objc, they specifically need the 'weak' designation, where as if they were pure swift protocols that is not necessary.  I could be completely wrong about that though.

**Comment by akkyie** [comment]
It's now fixed (f4fb2517208bc0db7d75a2cc4a80183be9706b0f,) thanks a lot for your advice!
